apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: store-simulator-view
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: view
subjects:
- kind: ServiceAccount
  name: store-simulator