apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-env-cm
data:
  ITEM_INVENTORY_TOPIC: item.inventory
  STORE_INVENTORY_TOPIC: store.inventory
  ITEMS_TOPIC: items
  KAFKA_BOOTSTRAP_SERVERS: 'amq-kafka-kafka-bootstrap.amq-streams.svc:9092'
  